# Generated by Django 6.0.3 on 2026-03-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('wind_speed', models.FloatField()),
                ('seismic_zone', models.CharField(max_length=10)),
                ('seismic_factor', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
            ],
        ),
    ]
